name: Crear APK Android

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Caleb-Space-Dominion-GitHub-Android

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Instalar dependencias
        run: npm install

      - name: Crear proyecto Android
        run: npx cap add android

      - name: Compilar APK
        run: cd android && chmod +x gradlew && ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Caleb-Space-Dominion-APK
          path: Caleb-Space-Dominion-GitHub-Android/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
